### ISSUE TITLE
DatePicker crashes with Accompanist version 0.24.11-rc

### ISSUE THREAD

**Issue by EBfVince** [vanpra/compose-material-dialogs#156]
**Describe the bug**
DatePicker crashes when using compose-material-dialogs version `0.8.0-beta` and Accompanist version `0.24.11-rc`.

**To Reproduce**
Compose version : `1.2.0-rc01`

build.gradle
```gradle
// Accompanist
def accompanist_version = "`0.24.11-rc"
implementation "com.google.accompanist:accompanist-systemuicontroller:$accompanist_version"
implementation "com.google.accompanist:accompanist-pager:$accompanist_version"

// Compose Material Dialog DateTime
implementation "io.github.vanpra.compose-material-dialogs:datetime:0.8.0-beta"
```

Open the date picker dialog, and it immediately crashes.

```
FATAL EXCEPTION: main
Process: com.ebf.daily, PID: 4827
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/compose/foundation/lazy/grid/LazyGridScope$DefaultImpls;
	at com.vanpra.composematerialdialogs.datetime.date.DatePickerKt$DayOfWeekHeader$1$1.invoke(DatePicker.kt:397)
	at com.vanpra.composematerialdialogs.datetime.date.DatePickerKt$DayOfWeekHeader$1$1.invoke(DatePicker.kt:395)
	at androidx.compose.foundation.lazy.grid.LazyGridItemProviderImplKt$rememberItemProvider$2$1.invoke(LazyGridItemProviderImpl.kt:59)
	at androidx.compose.foundation.lazy.grid.LazyGridItemProviderImplKt$rememberItemProvider$2$1.invoke(LazyGridItemProviderImpl.kt:58)
...
```

**Notes**
It works well with Compose version `1.2.0-rc01` and Accompanist version `0.24.10-beta`. 
The crash happen after upgrading accompanist to `0.24.11-rc`.

**Expected behaviour**
No crash with the latest version of accompanist (`0.24.11-rc`).

**Please complete the following information about your device:**
 - Name: Realme 7
 - Android Version: Android 11

**Additional context**
I think you just need to upgrade the accompanist version that you are using in the library (actually `"0.24.9-beta"`) to the latest version.

**Comment by StuStirling** [comment]
Also happens when using Accompanist version `0.24.12-rc`

**Comment by Mehly** [comment]
I'm having the same crash with the following setup:

- accompanist version: `0.24.12-rc`
- `implementation "io.github.vanpra.compose-material-dialogs:datetime:0.8.0-beta"`

**Comment by basilisfou** [comment]
Having the same crash with 

- accompanist version 0.24.13-rc
- compose version 1.2.0-rc03
- datetime 0.8.0-beta

**Comment by Syer10** [comment]
Compose 1.2.0 stabilized the lazy grid which the DatePicker uses, and therefor the library needs to be updated to the new version of compose. Which will probably only happen when Compose 1.2 is fully released.

**Comment by vanpra** [comment]
This should be fixed in 0.8.1-rc
